### PR TITLE
Added Description(Rosa)

### PR DESCRIPTION
**Pull request by roschristen**

### CODE REVIEW

**Comment by ClevelandHighSchool** [comment]
I have changed the entire setup to be a "Markup" style page which autogenerates.  Cancel this request and make a new one in that format.  Take a look at the page :)

**Comment by roschristen** [comment]
Ok, will do!

**Comment by roschristen** [comment]
Hey! I checked out the file and the syntax doesn't seem too confusing, but
I'm confused as to which file I'm supposed to be editing. The index file
looks like the right one but it doesn't have any code that pertains to what
appears on the page. Unless the window.location function is doing something?

**Comment by roschristen** [comment]
Nevermind I think I get it now. Forgot to read file names. I'm assuming I'm
supposed to edit the readme.md file.
(Hopefully I'm not wrong about that)

**Comment by ClevelandHighSchool** [comment]
You are correct, will remove the index file :)

**Pull request closed without merging**
